.github/workflows/deploy-prod.yml
.github/workflows/gradle-CI.yml
build.gradle.kts
src/main/kotlin/com/petqua/application/banner/BannerDtos.kt
src/main/kotlin/com/petqua/application/banner/BannerService.kt
src/main/kotlin/com/petqua/application/banner/dto/BannerDtos.kt
src/main/kotlin/com/petqua/common/cofig/CacheConfiguration.kt
src/main/kotlin/com/petqua/domain/banner/Banner.kt
src/main/kotlin/com/petqua/domain/banner/BannerRepository.kt
src/main/kotlin/com/petqua/presentation/banner/BannerController.kt
src/test/kotlin/com/petqua/application/banner/BannerServiceTest.kt
src/test/kotlin/com/petqua/presentation/banner/BannerControllerTest.kt
src/test/kotlin/com/petqua/test/ApiTestConfig.kt

- closed #16 
- 홈 화면에서 사용 배너 정보를 제공하는 API 개발
- `Spring Cache`를 통해 배너 정보 caching
- 워크플로우 수정
- CI의 경우 push하는 경우에만 수행되도록 변경하였습니다. 보통 push -> PR을 생성하니깐 동일한 작업이 2번 돌더라고요.
- CD의 경우 docker image가 삭제 되지 않는 현상이 발견되어서 image를 지우는 option을 추가하였습니다.
- 배포시 table이 생성되어 있지 않아 임시로 `ddl-auto: create`를 추가하였습니다.
ApiTestConfig를 추가했습니다! [7c74c6b](https://github.com/petqua/backend/pull/18/commits/7c74c6bf1d098f95fe7dc5eacb2551891ba61dbb)
공통으로 설정되는 부분들 (`@SpringBootTest(web ..), dataCleaner, afterContainer)을 공통화 해보았습니다.
BehaviorSpec을 상속하는 구조이다 보니, 추가하기 어려웠는데요. 달라진 점은 아래와 같습니다!
AS-IS
```kotlin
@SpringBootTest(webEnvironment = RANDOM_PORT)
class BannerControllerTest(
@LocalServerPort private val port: Int,
private val bannerRepository: BannerRepository,
private val dataCleaner: DataCleaner,
) : BehaviorSpec({ …
```

feature: 배너 이미지 조회

---

src/main/kotlin/com/petqua/application/announcement/AnnouncementDtos.kt
src/main/kotlin/com/petqua/application/announcement/AnnouncementService.kt
src/main/kotlin/com/petqua/common/cofig/CacheConfiguration.kt
src/main/kotlin/com/petqua/domain/announcement/Announcement.kt
src/main/kotlin/com/petqua/domain/announcement/AnnouncementRepository.kt
src/main/kotlin/com/petqua/presentation/announcement/AnnouncementController.kt
src/test/kotlin/com/petqua/application/announcement/AnnouncementServiceTest.kt
src/test/kotlin/com/petqua/application/product/ProductServiceTest.kt
src/test/kotlin/com/petqua/presentation/announcement/AnnouncementControllerTest.kt
src/test/kotlin/com/petqua/presentation/product/ProductControllerTest.kt
src/test/kotlin/com/petqua/test/ApiTestConfig.kt

- closed #19 
- 공지 사항 조회 API 개발
~- on #18~

feature: 공지사항 조회

---

src/main/kotlin/com/petqua/common/config/DataInitializer.kt
src/test/resources/application.yml

- closed #22 
- DataInitializer 를 통해 dummy data 생성 로직을 추가했습니다.
- Postman 으로 dummy data 생성 및 조회 로직 테스트 했습니다.
[참고한 자료](https://engineerinsight.tistory.com/71) 입니다.

feature: DataInitializer 를 통해 dummy data 생성

---

build.gradle.kts
src/main/kotlin/com/petqua/application/cart/CartProductService.kt
src/main/kotlin/com/petqua/application/cart/dto/CartProductDtos.kt
src/main/kotlin/com/petqua/common/domain/Repository.kt
src/main/kotlin/com/petqua/common/util/Validate.kt
src/main/kotlin/com/petqua/domain/auth/LoginMember.kt
src/main/kotlin/com/petqua/domain/cart/CartProduct.kt
src/main/kotlin/com/petqua/domain/cart/CartProductQuantity.kt
src/main/kotlin/com/petqua/domain/cart/CartProductRepository.kt
src/main/kotlin/com/petqua/domain/cart/DeliveryMethod.kt
src/main/kotlin/com/petqua/exception/cart/CartProductException.kt
src/main/kotlin/com/petqua/exception/cart/CartProductExceptionType.kt
src/main/kotlin/com/petqua/exception/member/MemberException.kt
src/main/kotlin/com/petqua/exception/member/MemberExceptionType.kt
src/main/kotlin/com/petqua/presentation/auth/LoginArgumentResolver.kt
src/main/kotlin/com/petqua/presentation/cart/CartProductController.kt
src/main/kotlin/com/petqua/presentation/cart/dto/CartProductDtos.kt
src/main/kotlin/com/petqua/presentation/product/ProductController.kt
src/test/kotlin/com/petqua/application/cart/CartProductServiceTest.kt
src/test/kotlin/com/petqua/application/product/ProductServiceTest.kt
src/test/kotlin/com/petqua/domain/cart/CartProductQuantityTest.kt
src/test/kotlin/com/petqua/domain/product/ProductCustomRepositoryImplTest.kt
src/test/kotlin/com/petqua/domain/product/ProductTest.kt
src/test/kotlin/com/petqua/presentation/cart/CartProductControllerTest.kt
src/test/kotlin/com/petqua/test/ApiTestConfig.kt
src/test/kotlin/com/petqua/test/fixture/MemberFixtures.kt

- closed #25 
- 설명
- 봉달목록 도메인 추가
```kotlin
@Id @GeneratedValue(strategy = GenerationType.IDENTITY)
val id: Long = 0L,
@Column(nullable = false)
val memberId: Long,
@Column(nullable = false)
val productId: Long,
@Column(nullable = false)
val quantity: Int = 1,
@Column(nullable = false)
val isMale: Boolean,
@Enumerated(value = EnumType.STRING)
@Column(nullable = false)
val deliveryMethod: DeliveryMethod,
```
상품의 옵션이 `수량/암수구분/운송 방식`만 선택 가능하다고 생각하고 구현하였습니다.
추후 옵션이 추가 된다면  product_option을 테이블로 분리하고, product_option_id를 가지는 방식으로 수정할 생각입니다.
- 상품을 정해진 옵션에 따라 봉달 목록에 추가하는 API 구현
- `existByIdOrThrow`라는 확장함수 하나 추가했습니다. 042708bab1c302c1b1e5aea0e4c358a99a74b578
반환 값이 없는 검증용으로 사용 할 목적으로 만들었어요!
- ControllerTest에서 자주 사용될 로그인셋업 메서드를 추가하였습니다.
d942e40a7e824480df6204c2d37136f2c0e4b671
공통으로 사용되는 …

feature: 봉달목록에 상품 추가 api

---

src/main/kotlin/com/petqua/application/cart/CartProductService.kt
src/main/kotlin/com/petqua/application/cart/dto/CartProductDtos.kt
src/main/kotlin/com/petqua/domain/cart/CartProduct.kt
src/main/kotlin/com/petqua/domain/cart/CartProductQuantity.kt
src/main/kotlin/com/petqua/exception/cart/CartProductExceptionType.kt
src/main/kotlin/com/petqua/presentation/cart/CartProductController.kt
src/main/kotlin/com/petqua/presentation/cart/dto/CartProductDtos.kt
src/test/kotlin/com/petqua/application/cart/CartProductServiceTest.kt
src/test/kotlin/com/petqua/domain/auth/FakeKakaoOauthApiClient.kt
src/test/kotlin/com/petqua/domain/cart/CartProductTest.kt
src/test/kotlin/com/petqua/presentation/cart/CartProductControllerSteps.kt
src/test/kotlin/com/petqua/presentation/cart/CartProductControllerTest.kt
src/test/kotlin/com/petqua/test/fixture/CartProductFixtures.kt

- closed #26 
[작업 범위](https://github.com/petqua/backend/pull/34/files/b53c1f45fe971fa62ef2f7dab9d3bec413703347..ee0a8a63c24d40b07a3996b4480c1a8c8e38000d)
- 봉달 상품의 옵션을 수정하는 API 구현
권한 검증, 옵션 요청에 대한 유효값 검증 포함
- ControllerTest steps 방식 추가
ControllerTest에서 테스트 시 요구되는 사항들이 있었습니다.
봉달 상품 수정을 테스트 하기 위해선 `회원, 상품, 봉달 상품` 이 존재해야 했는데요. (이런 케이스는 많을 예정..)
봉달 상품 저장 역시 `Repository`를 통해 `save()`하려 했는데, 유효한 memberId가 필요했었습니다.
회원의 경우 id를 지정하여 `save()` 할 수 있지만, API요청에 사용 되는 accessToken과 지정한 member의 id가 다를 수 있더라구요!
ex)
```kotlin
val member = MemberRepository.save(member(id = 1L))
val memberAuthResponse = signInAsMember()
// memberAuthResponse.accessToken의 서명된 Id와 member.id가 다를 수 있음
header(HttpHeaders.AUTHORIZATION, accessToken) // accessToken 요청
patch("/carts/items/{cartProductId}/options", cartProductId) // …
```

feature: 봉달 목록내 상품 수정 api

---

src/main/kotlin/com/petqua/application/cart/CartProductService.kt
src/main/kotlin/com/petqua/application/cart/dto/CartProductDtos.kt
src/main/kotlin/com/petqua/common/util/EntityManagerUtils.kt
src/main/kotlin/com/petqua/domain/cart/CartProductCustomRepository.kt
src/main/kotlin/com/petqua/domain/cart/CartProductCustomRepositoryImpl.kt
src/main/kotlin/com/petqua/domain/cart/CartProductRepository.kt
src/main/kotlin/com/petqua/domain/product/ProductCustomRepository.kt
src/main/kotlin/com/petqua/domain/product/ProductCustomRepositoryImpl.kt
src/main/kotlin/com/petqua/presentation/cart/CartProductController.kt
src/test/kotlin/com/petqua/application/cart/CartProductServiceTest.kt
src/test/kotlin/com/petqua/domain/product/ProductCustomRepositoryImplTest.kt
src/test/kotlin/com/petqua/presentation/cart/CartProductControllerSteps.kt
src/test/kotlin/com/petqua/presentation/cart/CartProductControllerTest.kt
src/test/kotlin/com/petqua/presentation/product/ProductControllerTest.kt
src/test/kotlin/com/petqua/test/fixture/CartProductFixtures.kt
src/test/kotlin/com/petqua/test/fixture/MemberFixtures.kt

- closed #28 
- 봉달에 담겨 있는 상품 조회 API 구현
간접 참조로 되어 있는 product를 조회하기 위해 `findAllProductResponseByIdIn()`을 추가 했습니다.
- 테스트 fixture 개선
fixture에서 `id = 1L`로 지정하다 보니 생성하고 저장할 때 동일한 객체로 판단해서 update 쿼리가 날아가는 이슈를 겪었습니다.. 수정했어요! 948eaf8ce18893ff6f06fe93a46b082b1449b6f3
~- on #37~

feature: 봉달 목록 조회 api

---

src/main/kotlin/com/petqua/application/auth/AuthService.kt
src/main/kotlin/com/petqua/common/config/WebConfig.kt
src/main/kotlin/com/petqua/common/util/WebUtils.kt
src/main/kotlin/com/petqua/domain/auth/token/AuthTokenProvider.kt
src/main/kotlin/com/petqua/domain/auth/token/JwtProvider.kt
src/main/kotlin/com/petqua/exception/auth/AuthExceptionType.kt
src/main/kotlin/com/petqua/presentation/auth/AuthController.kt
src/main/kotlin/com/petqua/presentation/auth/AuthExtractor.kt
src/main/kotlin/com/petqua/presentation/auth/LoginArgumentResolver.kt
src/main/kotlin/com/petqua/presentation/auth/TokenArgumentResolver.kt
src/test/kotlin/com/petqua/application/auth/AuthServiceTest.kt
src/test/kotlin/com/petqua/domain/auth/AuthTokenProviderTest.kt
src/test/kotlin/com/petqua/presentation/auth/AuthControllerTest.kt
src/test/kotlin/com/petqua/presentation/cart/CartProductControllerSteps.kt
src/test/kotlin/com/petqua/presentation/product/WishProductControllerTest.kt
src/test/kotlin/com/petqua/test/ApiTestConfig.kt

- closed #43 
- Authorization 에서 Bearer prefix 를 파싱하는 로직을 추가했습니다.
- 관련 테스트도 수정했습니다.
- 홍고의 심부름도 했습니다!
- 홍고 코드 이것저것 건드려버렸는데 혹시 제가 의도와 다르게 바꾼 게 있다면 꼭 말씀해주세요!
- import 에서 wildcard 무슨 짓을 해도 다시 변경 되는데 어떻게 하면 좋을까요?

feature: Authorization 헤더 파싱 로직 추가

---

src/main/kotlin/com/petqua/domain/product/dto/ProductDtos.kt

- closed #45 
- lastViewedId가 default 값으로 들어온 경우 null 로 설정하도록 로직을 짰습니다.

refactor: lastViewedId default 값 설정

---

build.gradle.kts
src/main/kotlin/com/petqua/application/announcement/AnnouncementDtos.kt
src/main/kotlin/com/petqua/application/banner/dto/BannerDtos.kt
src/main/kotlin/com/petqua/application/cart/dto/CartProductDtos.kt
src/main/kotlin/com/petqua/application/product/dto/ProductDtos.kt
src/main/kotlin/com/petqua/common/config/CorsConfig.kt
src/main/kotlin/com/petqua/common/config/SwaggerConfig.kt
src/main/kotlin/com/petqua/domain/auth/LoginMember.kt
src/main/kotlin/com/petqua/domain/product/dto/ProductDtos.kt
src/main/kotlin/com/petqua/presentation/announcement/AnnouncementController.kt
src/main/kotlin/com/petqua/presentation/auth/AuthController.kt
src/main/kotlin/com/petqua/presentation/auth/AuthDtos.kt
src/main/kotlin/com/petqua/presentation/banner/BannerController.kt
src/main/kotlin/com/petqua/presentation/cart/CartProductController.kt
src/main/kotlin/com/petqua/presentation/cart/dto/CartProductDtos.kt
src/main/kotlin/com/petqua/presentation/product/ProductController.kt
src/main/kotlin/com/petqua/presentation/product/WishProductController.kt
src/main/kotlin/com/petqua/presentation/product/WishProductDtos.kt
src/main/kotlin/com/petqua/presentation/product/dto/ProductDtos.kt

- closed #30 
- Swagger API 명세 설정 추가했습니다!
Swagger에서 Auth 관련 API 들은 테스트할 수 없거나 힘듭니다. 따라서 Auth 관련 API 들은 Hidden 처리했습니다.
redirect 페이지를 로드할 수 없습니다. CORS 에러를 마주하게 됩니다.
카카오에서 전달해주는 auth code를 받을 수 없습니다.
Swagger UI에서 refreshToken 을 서버에게 cookie로 전달할 수 없습니다. 다음 자료를 참고해주세요.
- https://github.com/tiangolo/fastapi/issues/880
- https://swagger.io/docs/specification/authentication/cookie-authentication/
> Note for Swagger UI and Swagger Editor users: Cookie authentication is currently not supported for "try it out" requests due to browser security restrictions. See [this issue](https://github.com/swagger-api/swagger-js/issues/1163) for more information. [SwaggerHub](https://swagger.io/tools/swaggerhub/) does not have this limitation.
- 각자 localhost 에서 테스트 해보셔도 좋을 것 같습니다!

feature: Swagger API 명세 추가

---

src/main/kotlin/com/petqua/presentation/auth/AuthController.kt
src/main/kotlin/com/petqua/presentation/auth/AuthDtos.kt

- closed #58 
- 프론트엔드 요청에 의해 Swagger에 Auth 관련 API 명세를 다시 추가했습니다.

refactor: Auth Swagger 명세 다시 추가

---

src/main/kotlin/com/petqua/presentation/auth/AuthController.kt
src/main/kotlin/com/petqua/presentation/auth/AuthDtos.kt
src/test/kotlin/com/petqua/presentation/auth/AuthControllerTest.kt
src/test/kotlin/com/petqua/test/ApiTestConfig.kt

- 설명
프론트 요청에 의해 auth 응답을 변경했습니다
* oauth redirectURI를 Location헤더에서 responseBody로 반환하게 변경 (status code 302 -> 200)
* accessToken을 responseBody에서 responseHeader로 반환하게 변경

refactor: auth 응답 변경

---

src/main/kotlin/com/petqua/common/query/ConnectionProxyHandler.kt
src/main/kotlin/com/petqua/common/query/PreparedStatementProxyHandler.kt
src/main/kotlin/com/petqua/common/query/QueryCounterAop.kt
src/main/kotlin/com/petqua/common/query/QueryInfo.kt

- closed #57
- 설명
하나의 API요청에서 발생한 쿼리 개수와 소요시간을 측정해서 로깅합니다.
예시 : `METHOD: GET, URI: products/wishes, QUERY_COUNT: 3, QUERY_TIME: 7`
예전에 쿼리카운터쓸 때 소요시간까지 로깅하는게 좋았어서 추가했습니다...! 
근데 소요시간 측정때문에 PreparedStatementProxyHandler가 추가됐네요...ㅎㅎ
(쿼리 개수만 카운팅 할 때 코드 참고: 65d2782782c6953a0896e0488f2e1be76458598e)
소요시간 로그에서 빼고 싶으시면 말씀해주십시오~~~

feature: 쿼리 카운터 구현

---

build.gradle.kts
src/main/kotlin/com/petqua/common/config/AccessLogConfig.kt
src/main/kotlin/com/petqua/common/config/MdcFilter.kt
src/main/kotlin/com/petqua/common/exception/ExceptionControllerAdvice.kt
src/main/resources/console-appender.xml
src/main/resources/error-appender.xml
src/main/resources/info-appender.xml
src/main/resources/logback-access.xml
src/main/resources/logback-spring.xml
src/main/resources/warn-appender.xml

- closed #68
로깅을 추가해보았습니다! 로거가 총 다섯 개 있어요
* `CONSOLE` :  모든 레벨의 로그를 콘솔에서 출력
* `FILE-ACCESS` : HTTP Request와 관련된 로그를 파일로 생성(HTTP status code가 400번 이상일 때만 로깅)
* `FILE-INFO` : INFO 레벨 로그를 파일로 생성
* `FILE-WARN` : WARN 레벨 로그를 파일로 생성
* `FILE-ERROR` : ERROR 레벨 로그를 파일로 생성(에러 스택 트레이스 전부 출력)
```
[requestId: 1930dbf2-e3c0-4171-ab13-7b21671e065d]
timestamp: 2024-02-13 04:56:47,
DELETE /carts/1 HTTP/1.1
content-type: application/json
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtZW1iZXJJZCI6IjIiLCJhdXRob3JpdHkiOiJNRU1CRVIiLCJpYXQiOjE3MDc3Njc4MjAsImV4cCI6MTcwNzc3MTQyMH0._ZZPlet59ljlnoZ7DBP5Rec2BDM4gqcNTBNGCwUZJ_w
accept: */*
host: localhost:52584
connection: Keep-Alive
user-agent: Apache-HttpClient/4.5.13 (Java/18.0.2)
accept-encoding: gzip,deflate
cookie: …
```

feature: 로깅 추가

---

src/main/kotlin/com/petqua/application/product/category/CategoryDto.kt
src/main/kotlin/com/petqua/application/product/category/CategoryService.kt
src/main/kotlin/com/petqua/common/config/DataInitializer.kt
src/main/kotlin/com/petqua/domain/auth/LoginMemberOrGuest.kt
src/main/kotlin/com/petqua/presentation/product/ProductController.kt
src/main/kotlin/com/petqua/presentation/product/category/CategoryController.kt
src/main/kotlin/com/petqua/presentation/product/category/CategoryDto.kt
src/main/kotlin/com/petqua/presentation/product/dto/ProductDtos.kt
src/test/kotlin/com/petqua/application/product/category/CategoryServiceTest.kt
src/test/kotlin/com/petqua/presentation/product/ProductControllerSteps.kt
src/test/kotlin/com/petqua/presentation/product/category/CategoryControllerSteps.kt
src/test/kotlin/com/petqua/presentation/product/category/CategoryControllerTest.kt
src/test/kotlin/com/petqua/test/TestUtil.kt

- closed #78 
- 상품 상세 조회, 카테고리 조건 상품 조회 API 에 대한 Swagger 설정이 누락되어 추가했습니다.
- 카테고리 조건 상품 조회 API는 LoginMemberOrGuest 도 추가했습니다.
- Swagger 테스트하는 김에 더미데이터 생성 로직을 변경했습니다. 나름 데이터 정합성을 맞추려고 노력했습니다!

refactor: 카테고리 조회 상품 상세 조회 api swagger 반영

---

src/main/kotlin/com/petqua/application/product/dto/ProductReviewDtos.kt
src/main/kotlin/com/petqua/application/product/review/ProductReviewService.kt
src/main/kotlin/com/petqua/domain/product/Product.kt
src/main/kotlin/com/petqua/domain/product/dto/ProductReviewDtos.kt
src/main/kotlin/com/petqua/domain/product/review/ProductReviewCustomRepository.kt
src/main/kotlin/com/petqua/domain/product/review/ProductReviewCustomRepositoryImpl.kt
src/main/kotlin/com/petqua/domain/product/review/ProductReviewStatistics.kt
src/main/kotlin/com/petqua/presentation/product/ProductReviewController.kt
src/test/kotlin/com/petqua/application/product/review/ProductReviewServiceTest.kt
src/test/kotlin/com/petqua/domain/product/review/ProductReviewCustomRepositoryImplTest.kt
src/test/kotlin/com/petqua/domain/product/review/ProductReviewStatisticsTest.kt
src/test/kotlin/com/petqua/presentation/product/ProductReviewControllerSteps.kt
src/test/kotlin/com/petqua/presentation/product/ProductReviewControllerTest.kt

- closed #52 
상품 후기 통계 조회 API 구현
- 상품 후기 데이터를 score로 groupBy 하여 개수를 집계하였습니다.
~- 만족도와 전체 후기 개수는 주어진 데이터로 계산 가능하다고 판단하여 응답에 포함하지 않았습니다.~
- 만족도와 전체 후기 개수, 별점 평균을 포함하여 응답합니다.
만족도는 전체 별점 중 4, 5 점 별점의 비율입니다.
응답 예시
```json
{
"scoreFiveCount": 3,
"scoreFourCount": 0,
"scoreThreeCount": 0,
"scoreTwoCount": 2,
"scoreOneCount": 0,
"productSatisfaction": 60,
"totalReviewCount": 5,
"averageScore": 3.8
}
```
- on #64 
응답 필드에 대한 네이밍이 괜찮으신가요...?

feature: 상품 후기 통계 조회 api

---

src/main/kotlin/com/petqua/application/product/dto/ProductReviewDtos.kt
src/main/kotlin/com/petqua/application/product/review/ProductReviewService.kt
src/main/kotlin/com/petqua/domain/product/review/ProductReviewRecommendationRepository.kt
src/main/kotlin/com/petqua/presentation/product/ProductReviewController.kt
src/main/kotlin/com/petqua/presentation/product/dto/ProductReviewDtos.kt
src/test/kotlin/com/petqua/application/product/review/ProductReviewServiceTest.kt

- closed #85 
- 설명
#51 에서 TODO로 남겨두었던 상품 후기 추천 여부 반영 로직을 추가하였습니다.
찬민님이 (#76)에서 만드셨던 `LoginOrGuest`를 활용하였습니다.

feat: 회원/비회에 따른 상품 후기 조회시 추천 여부 포함하여 응답

---

src/main/kotlin/com/petqua/common/config/DataInitializer.kt
src/main/kotlin/com/petqua/domain/product/dto/ProductReviewDtos.kt
src/main/kotlin/com/petqua/domain/product/review/ProductReview.kt
src/main/kotlin/com/petqua/domain/product/review/ProductReviewCustomRepositoryImpl.kt
src/main/kotlin/com/petqua/domain/product/review/ProductReviewDynamicJpqlGenerator.kt
src/main/kotlin/com/petqua/domain/product/review/ProductReviewScore.kt
src/main/kotlin/com/petqua/exception/product/review/ProductReviewExceptionType.kt
src/test/kotlin/com/petqua/domain/product/review/ProductReviewScoreTest.kt
src/test/kotlin/com/petqua/test/fixture/ProductReviewFixtures.kt

- closed #90 
- 상품 후기의 초기 데이터 별점이 1-5 사이 값을 가지도록 수정
- 상품 별점에 대한 값 객체 적용

fix: 초기 데이터 리뷰 별점 수정

---

src/main/kotlin/com/petqua/application/product/dto/ProductReviewDtos.kt
src/main/kotlin/com/petqua/application/product/review/ProductReviewService.kt
src/main/kotlin/com/petqua/domain/order/Order.kt
src/main/kotlin/com/petqua/domain/order/OrderDeliveryInfo.kt
src/main/kotlin/com/petqua/domain/order/OrderNumber.kt
src/main/kotlin/com/petqua/domain/order/OrderPayment.kt
src/main/kotlin/com/petqua/domain/order/OrderProductInfo.kt
src/main/kotlin/com/petqua/domain/order/OrderShippingAddressInfo.kt
src/main/kotlin/com/petqua/domain/order/OrderStatus.kt
src/main/kotlin/com/petqua/domain/payment/tosspayment/TossPayment.kt
src/main/kotlin/com/petqua/domain/payment/tosspayment/TossPaymentMethod.kt
src/main/kotlin/com/petqua/domain/payment/tosspayment/TossPaymentStatus.kt
src/main/kotlin/com/petqua/domain/payment/tosspayment/TossPaymentType.kt
src/main/kotlin/com/petqua/domain/product/review/ProductReviewRecommendationRepository.kt
src/main/kotlin/com/petqua/presentation/product/ProductReviewController.kt
src/main/kotlin/com/petqua/presentation/product/dto/ProductReviewDtos.kt
src/test/kotlin/com/petqua/application/product/review/ProductReviewServiceTest.kt

- closed #84
상품 주문과 결제 정보 관련 데이터 구조 설계
- 설명
주문에 대해 고민을 깊게 했는데요.
고려할 요소도 많고 복잡하네요...
우선 당장 필요한 부분들만 고려하여 도메인을 구성하고, 추후 결제와 주문 접수 과정에서 필요한 값들을 추가하겠습니다.
간단하게 주문-결제 플로우를 알아보면 아래와 같습니다.
```
주문 접수 -> PG사 결제 요청 ->  결제 성공 -> 결제 최종 승인 -> 주문 완료
|
ᄂ> 결제 실패 -> 실패 처리
```
아래 토스메이먼츠에서 제공하는 플로우도 참고하면 좋아요!
https://docs.tosspayments.com/guides/payment-widget/integration
---
위 과정을 고려해서
- 사용자의 주문을 저장하는 `Order`,
- PG사로부터 받은 결제 저옵를 저장하는 `TossPayment`, (toss 페이먼츠를 사용하여 구체 이름을 사용하였습니다)
- [주문]과 [결제]를 연관 짓는 `OrderPayment`
총 3개의 도메인이 추가되었습니다.
도메인에 대해 기술하고, 주석으로 해당 필드에 대한 설계의도를 남겨둘게요!
---
<br/><br/><br/>
```kotlin
@Table(name = "orders") // MySql의 order 예약어와 겹쳐서 추가했습니다.
@Entity
class Order(
@Id @GeneratedValue(strategy = IDENTITY)
val id: Long = 0L,
@Column(nullable = false)
val memberId: Long,
@Embedded …
```

feature: 주문 도메인 설계

---

src/main/kotlin/com/petqua/application/product/ProductService.kt
src/main/kotlin/com/petqua/application/product/dto/ProductDtos.kt
src/main/kotlin/com/petqua/common/config/DataInitializer.kt
src/main/kotlin/com/petqua/domain/product/Product.kt
src/main/kotlin/com/petqua/domain/product/ProductCustomRepository.kt
src/main/kotlin/com/petqua/domain/product/ProductCustomRepositoryImpl.kt
src/main/kotlin/com/petqua/domain/product/detail/description/ProductDescription.kt
src/main/kotlin/com/petqua/domain/product/detail/description/ProductDescriptionContent.kt
src/main/kotlin/com/petqua/domain/product/detail/description/ProductDescriptionRepository.kt
src/main/kotlin/com/petqua/domain/product/detail/description/ProductDescriptionTitle.kt
src/main/kotlin/com/petqua/domain/product/detail/image/ImageType.kt
src/main/kotlin/com/petqua/domain/product/detail/image/ProductImage.kt
src/main/kotlin/com/petqua/domain/product/detail/image/ProductImageRepository.kt
src/main/kotlin/com/petqua/domain/product/detail/info/DifficultyLevel.kt
src/main/kotlin/com/petqua/domain/product/detail/info/OptimalTankSize.kt
src/main/kotlin/com/petqua/domain/product/detail/info/OptimalTemperature.kt
src/main/kotlin/com/petqua/domain/product/detail/info/ProductInfo.kt
src/main/kotlin/com/petqua/domain/product/detail/info/ProductInfoRepository.kt
src/main/kotlin/com/petqua/domain/product/detail/info/Temperament.kt
src/main/kotlin/com/petqua/domain/product/dto/ProductDtos.kt
src/main/kotlin/com/petqua/domain/product/option/ProductOption.kt
src/test/kotlin/com/petqua/application/product/ProductServiceTest.kt
src/test/kotlin/com/petqua/domain/product/ProductCustomRepositoryImplTest.kt
src/test/kotlin/com/petqua/presentation/product/ProductControllerTest.kt
src/test/kotlin/com/petqua/test/fixture/ProductFixtures.kt

- closed #87 
- 상품 상세 조회 API의 응답을 변경했습니다.
```json
{
"id": 98,
"name": "팬시구피1",
"family": "송사리과",
"species": "팬시구피",
"price": 80000,
"storeName": "상점1",
"discountRate": 50,
"discountPrice": 40000,
"wishCount": 100,
"reviewCount": 4,
"reviewAverageScore": 2.5,
"imageUrls": [
"https://docs.petqua.co.kr/products/thumbnails/image1.jpeg",
"https://docs.petqua.co.kr/products/thumbnails/image2.jpeg",
"https://docs.petqua.co.kr/products/thumbnails/image3.jpeg"
],
"descriptionTitle" : "설명 제목",
"descriptionContent": "설명 내용",
"descriptionImageUrls" : [
"https://docs.petqua.co.kr/products/thumbnails/image1.jpeg",
"https://docs.petqua.co.kr/products/thumbnails/image2.jpeg",
],
"canDeliverSafely": false,
"canDeliverCommonly": false,
"canPickUp": false,
"optimalTemperatureMin": 22, …
```

refactor: 상품 상세 조회 api 응답 필드 수정

---

src/main/kotlin/com/petqua/common/config/DataInitializer.kt
src/main/kotlin/com/petqua/presentation/order/OrderController.kt
src/test/kotlin/com/petqua/domain/product/ProductTest.kt

- closed #103 
- 상품 옵션 더미 데이터가 없어서, 상품 상세 조회 api 가 제대로 동작하지 않습니다. 따라서 더미 데이터 생성 로직을 추가했습니다.
- 출력을 포함한 테스트를 삭제했습니다.
- 간단히 Swagger 를 애노테이션을 붙여두었습니다.

fix: 상품 옵션 더미 데이터 추가 로직 변경

---

src/main/kotlin/com/petqua/application/cart/CartProductService.kt
src/main/kotlin/com/petqua/application/cart/dto/CartProductDtos.kt
src/main/kotlin/com/petqua/application/product/ProductService.kt
src/main/kotlin/com/petqua/application/product/dto/ProductDtos.kt
src/main/kotlin/com/petqua/common/util/BigDecimalUtils.kt
src/main/kotlin/com/petqua/domain/cart/CartProduct.kt
src/main/kotlin/com/petqua/domain/cart/CartProductRepository.kt
src/main/kotlin/com/petqua/domain/product/ProductCustomRepositoryImpl.kt
src/main/kotlin/com/petqua/domain/product/dto/ProductDtos.kt
src/main/kotlin/com/petqua/domain/product/option/ProductOptionRepository.kt
src/main/kotlin/com/petqua/exception/cart/CartProductExceptionType.kt
src/main/kotlin/com/petqua/presentation/cart/CartProductController.kt
src/main/kotlin/com/petqua/presentation/cart/dto/CartProductDtos.kt
src/test/kotlin/com/petqua/application/cart/CartProductServiceTest.kt
src/test/kotlin/com/petqua/application/product/ProductServiceTest.kt
src/test/kotlin/com/petqua/domain/cart/CartProductTest.kt
src/test/kotlin/com/petqua/domain/product/ProductCustomRepositoryImplTest.kt
src/test/kotlin/com/petqua/presentation/cart/CartProductControllerSteps.kt
src/test/kotlin/com/petqua/presentation/cart/CartProductControllerTest.kt
src/test/kotlin/com/petqua/presentation/product/ProductControllerTest.kt
src/test/kotlin/com/petqua/test/fixture/CartProductFixtures.kt
src/test/kotlin/com/petqua/test/fixture/OrderFixture.kt
src/test/kotlin/com/petqua/test/fixture/ProductFixtures.kt

- closed #102 
- 설명
봉달 목록 관련하여 응답 데이터를 수정하였습니다.
AS-IS
```json
{
"id": 3,
"storeName": "store",
"productId": 3,
"productName": "쿠아3",
"productThumbnailUrl": "image.jpg",
"productPrice": 1,
"productDiscountRate": 0,
"productDiscountPrice": 1,
"quantity": 1,
"isMale": true,
"deliveryMethod": "COMMON",
"isOnSale": true
},
```
TO-BE
```json
{
"id": 3,
"storeName": "store",
"productId": 3,
"productName": "쿠아3",
"productThumbnailUrl": "image.jpg",
"productPrice": 1,
"productDiscountRate": 0,
"productDiscountPrice": 1,
"quantity": 1,
"sex": "MALE",
"deliveryMethod": "COMMON",
"deliveryFee": 3000.00,
"isOnSale": true,
"safeDeliveryFee": null,
"commonDeliveryFee": 3000.00,
"pickUpDeliveryFee": null,
"maleAdditionalPrice": 0.00,
"femaleAdditionalPrice": 3000.00
},
```
성별이 단순 boolean이 아닌 Enum으로 변경됨에 …

feature: 봉달 관련 api 스펙 수정

---

build.gradle.kts
src/main/kotlin/com/petqua/application/announcement/AnnouncementDtos.kt
src/main/kotlin/com/petqua/application/banner/dto/BannerDtos.kt
src/main/kotlin/com/petqua/common/config/CacheConfig.kt
src/main/kotlin/com/petqua/common/config/RedisConfig.kt
src/main/kotlin/com/petqua/domain/product/ProductCustomRepositoryImpl.kt
src/main/kotlin/com/petqua/domain/product/category/CategoryCustomRepositoryImpl.kt
src/main/kotlin/com/petqua/domain/product/option/Sex.kt
src/test/kotlin/com/petqua/application/announcement/AnnouncementServiceTest.kt
src/test/kotlin/com/petqua/application/banner/BannerServiceTest.kt
src/test/kotlin/com/petqua/application/product/ProductServiceTest.kt
src/test/kotlin/com/petqua/test/DataCleaner.kt
src/test/kotlin/com/petqua/test/config/RedisContainer.kt
src/test/kotlin/com/petqua/test/config/RedisContainerConfig.kt
src/test/kotlin/com/petqua/test/config/TestConfig.kt
src/test/resources/application.yml

- closed #95 
- Redis 추가
ElasticCache를 도입하여 production 환경에서 사용할 cache memory를 추가하였습니다.
기존 `ConcurrentHashMap`으로 구현된 기본 Spring cache 대신, Redis를 cache 메모리로 사용 하도록 변경 하였습니다. fe2836c51cf9a075ddc915469939b7251d3107ee
Kotlin에서 json 응답을 캐싱할 때, Json객체로 역직렬화를 하지 못하는 이슈가 있었습니다.
`@JsonProperty` 를 추가하여 이슈를 해결하였습니다. 7f01d0a9310364d8f2b027617716a0ae0beb8ad8
count 쿼리에 대한 캐싱도 적용 하였습니다. fd63b30ffd5fec8fd0640328fdec9f38a67d9644
로컬에서 테스트 실행 시, redis가 필요하여 testcontainer를 통해 구축 하였습니다.
테스트 실행 할 때, docker가 실행중이어야 합니다..!

infra: redis 캐싱 적용

---

src/main/kotlin/com/petqua/application/notification/NotificationService.kt
src/main/kotlin/com/petqua/application/notification/dto/NotificationDtos.kt
src/main/kotlin/com/petqua/common/config/DataInitializer.kt
src/main/kotlin/com/petqua/domain/notification/Notification.kt
src/main/kotlin/com/petqua/domain/notification/NotificationCustomRepository.kt
src/main/kotlin/com/petqua/domain/notification/NotificationCustomRepositoryImpl.kt
src/main/kotlin/com/petqua/domain/notification/NotificationDynamicJpqlGenerator.kt
src/main/kotlin/com/petqua/domain/notification/NotificationRepository.kt
src/main/kotlin/com/petqua/exception/notification/NotificationException.kt
src/main/kotlin/com/petqua/exception/notification/NotificationExceptionType.kt
src/main/kotlin/com/petqua/presentation/notification/NotificationController.kt
src/main/kotlin/com/petqua/presentation/notification/dto/NotificationDtos.kt
src/test/kotlin/com/petqua/application/notification/NotificationServiceTest.kt
src/test/kotlin/com/petqua/presentation/notification/NotificationControllerSteps.kt
src/test/kotlin/com/petqua/presentation/notification/NotificationControllerTest.kt
src/test/kotlin/com/petqua/test/fixture/NotificationFixture.kt

- closed #111 
- 알림 관련 API 추가
[읽지 않은 알림 개수 조회 API] 결과를 캐싱 해두었습니다. 메인 페이지나 헤더에서 개수가 자주 필요할 것 같아서요..!
그래서 변동이 발생할 때, 캐싱을 비우는 로직을 추가하였습니다.
현재 읽지 않은 알림 개수의 변동이 존재하는 경우는 알림을 읽은 경우인데요. 이 로직에 캐싱을 비우도록 @CacheEvict를 사용하였습니다!

feature: 알림 조회 및 읽음 처리 api

---

src/main/kotlin/com/petqua/application/cart/CartProductService.kt
src/main/kotlin/com/petqua/application/cart/dto/CartProductDtos.kt
src/main/kotlin/com/petqua/presentation/cart/dto/CartProductDtos.kt
src/test/kotlin/com/petqua/application/cart/CartProductServiceTest.kt
src/test/kotlin/com/petqua/presentation/cart/CartProductControllerTest.kt
src/test/kotlin/com/petqua/test/fixture/CartProductFixtures.kt

- closed #116 
- 설명
봉달 목록에 상품의 옵션을 수정할 때 수량만 다른 경우도 중복을 처리하는 로직 수정
상품, 성별, 배송 방식, 수량까지 모두 같은 경우에만 중복으로 판단하도록 변경

fix: 봉달 상품 수정시 수량을 포함 하여 중복 검사 하도록 수정

---

src/main/kotlin/com/petqua/application/auth/AuthFacadeService.kt
src/main/kotlin/com/petqua/application/auth/AuthService.kt
src/main/kotlin/com/petqua/domain/auth/token/BlackListTokenCacheStorage.kt
src/main/kotlin/com/petqua/domain/member/Member.kt
src/main/kotlin/com/petqua/exception/auth/AuthExceptionType.kt
src/main/kotlin/com/petqua/presentation/auth/AuthController.kt
src/main/kotlin/com/petqua/presentation/auth/AuthExtractor.kt
src/main/kotlin/com/petqua/presentation/auth/TokenArgumentResolver.kt
src/test/kotlin/com/petqua/application/auth/AuthFacadeServiceTest.kt
src/test/kotlin/com/petqua/domain/auth/token/BlackListTokenCacheStorageTest.kt
src/test/kotlin/com/petqua/domain/member/MemberTest.kt
src/test/kotlin/com/petqua/presentation/auth/AuthControllerSteps.kt
src/test/kotlin/com/petqua/presentation/auth/AuthControllerTest.kt
src/test/kotlin/com/petqua/test/DataCleaner.kt

- closed #118 
- 로그아웃 API 구현
로그아웃 시, 회원의 oauth 토큰 정보와 리프레시 토큰을 초기화 하였습니다.
추가로 사용중이던 인증정보에 대해 `사용할 수 없는(블랙리스트)` 인증 정보로 관리 되도록 구성하였습니다.
블랙리스트 토큰 관리를 위해 Redis에 인증 정보들을 저장하였습니다.
저장 형식은 아래와 같습니다.
```
key - value
"member:${id}:accessToken" - "emj123mmnad0Bsd1.anboauhoEm1SVas.abahhjiaknl"
```
만료 시간은 accessToken의 만료시간과 동일하게 구성하였습니다!

feature: 로그아웃 api

---

src/main/kotlin/com/petqua/domain/keyword/ProductKeywordCustomRepositoryImpl.kt

- closed #121 
- 회원가입 API 에서 어종 검색 기능을 개발하면서 기획의 변경이 생겨서 이를 반영했습니다.
상품 검색 시에도 다음과 같은 정렬 조건을 따릅니다.
1. 검색어의 위치 오름차순
2. 글자수 오름차순
3. 글자 오름차순

refactor: 상품 검색 시 정렬 조건 변경

---

src/main/kotlin/com/petqua/application/order/OrderService.kt
src/main/kotlin/com/petqua/application/order/dto/OrderDtos.kt
src/main/kotlin/com/petqua/common/util/MapUtils.kt
src/main/kotlin/com/petqua/domain/order/OrderPaymentRepository.kt
src/main/kotlin/com/petqua/presentation/order/OrderController.kt
src/main/kotlin/com/petqua/presentation/order/dto/OrderDtos.kt
src/test/kotlin/com/petqua/application/order/OrderServiceTest.kt
src/test/kotlin/com/petqua/presentation/order/OrderControllerSteps.kt
src/test/kotlin/com/petqua/presentation/order/OrderControllerTest.kt

- closed #124 
주문번호로 조회시, 상세 주문 내역 응답 API를 개발했습니다.
응답 예시
```json
{
"orderNumber": "20240502000307AAAA7513EFAD",
"orderedAt": "2024-05-02T00:03:07.685322",
"orderProducts": [
{
"orderId": 1,
"orderStatus": "ORDER_CREATED",
"productId": 1,
"storeId": 1,
"storeName": "storeA",
"thumbnail": "image.jpg",
"productName": "1",
"quantity": 1,
"sex": "FEMALE",
"orderPrice": 1,
"price": 1,
"deliveryFee": 3000,
"deliveryMethod": "COMMON"
},
{
"orderId": 2,
"orderStatus": "ORDER_CREATED",
"productId": 2,
"storeId": 1,
"storeName": "storeA",
"thumbnail": "image.jpg",
"productName": "2",
"quantity": 1,
"sex": "MALE",
"orderPrice": 1,
"price": 1,
"deliveryFee": 3000,
"deliveryMethod": "COMMON"
}
],
"totalAmount": 3002
}
```

feature: 주문 상세 내역 조회 api
